### ISSUE TITLE
Add Option to Show Relevant Commits via git show

### ISSUE THREAD

**Issue by sshaw** [serch/gistory#6]
Hi, most of the time I use `gistory` then take the resulting SHAs and view them via `git show`. 

Would be nice to have an option, say `-o` that will open each relevant SHA (or whatever `-m` is) via `git show`. 

`git show` accepts multiple SHAs but it will output them all together. I think it's better to do them one at a time but I think either way having `gistory` ~option~ output them would be great.

**Comment by serch** [comment]
thanks for the suggestion! what about having instead a `--raw` switch that only outputs the commit hashes, this way one could pipe them to git show, git log, or anywhere else, like so:

`gistory --raw sidekiq | xargs git show`

**Comment by sshaw** [comment]
Yeah that makes sense. Though maybe you can just detect if stdout is a TTY and if not output the "raw" format. 

If you do this maybe an option like `--pretty` is necessary to force the default output even ~in~ if stdout is not tty.

**Comment by serch** [comment]
the feature was added in version v0.3.0, the option switch is --hashes-only: `gistory --hashes-onlysidekiq | xargs git show`
